## Python

In [4]:
print("Hello world")

Hello world


In [5]:
# assign variable with value
x = 2
x

2

## function

In [8]:
def simple_add(x, y):
    """The functio is to compute the sum of 2 numbers"""
    return (x+y)

In [18]:
simple_add(0, 1)

1

# Data type

In [10]:
x = 2
y = 3.142
z = True
z1 = 2j
z2 = "I am insane"

print(type(x))
print(type(y))
print(type(z))
print(type(z1))
print(type(z2))

x, y, z, z1, z2 = 1, 3.142, True, 2j, "I am insane"

<class 'int'>
<class 'float'>
<class 'bool'>
<class 'complex'>
<class 'str'>


In [13]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [14]:
x
y
z

1

3.142

True

# casting

In [17]:
x = 1.99
y = "-7.3"

print(int(x))
print(float(y))

1
-7.3


# List and Tuple

In [20]:
mylist = ["a", "b", "c"]
mytuple = ("a", "b", "c")

mylist[0]
mytuple[0]

'a'

'a'

In [21]:
mylist[0] = 1
print(mylist)

[1, 'b', 'c']


In [22]:
mytuple[0] = 1
print(mytuple)

TypeError: 'tuple' object does not support item assignment

# Numpy function

In [23]:
import numpy as np

In [24]:
a = np.array([1, 2, 3, 4]) 
a

array([1, 2, 3, 4])

In [25]:
# for debugging purpose, they are 2 important attributes in numpy array
a.shape

(4,)

* 0D.array --> () (scalar)
* 1D.array --> (4,) (vector)
* 2D.array --> (2, 3) (matrix)
* 3D.array --> (4, 2, 3) (tensor) (images normally have 3 color channel)

In [26]:
a.dtype

dtype('int32')

In [27]:
type(a)

numpy.ndarray

In [29]:
b = np.array(["a", 1, 2])
b[0]
b[1]

'a'

'1'

In [32]:
b.dtype

dtype('<U11')

In [37]:
a1 = np.array([5, 6, 7, 8])
a_long = np.concatenate((a, a1))
a_long

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
print(f"The shape of the new array is {a_long.shape}")

The shape of the new array is (8,)


In [49]:
def checkoddeven(x):
    if isinstance(x, int): 
        if x % 2 == 0:
            print(f"{x} is an even number")
        else: 
            print(f"{x} is an odd number")
    else:
        print(f"{x} is not an interger")        

In [53]:
checkoddeven(6)

6 is an even number


In [54]:
numpy_array = np.arange(1e06)
python_list = list(range(int(1e06)))

%time for _ in range(10): numpy_array*2

CPU times: total: 15.6 ms
Wall time: 28.9 ms


In [55]:
%time for _ in range(10): python_list*2

CPU times: total: 312 ms
Wall time: 314 ms


In [59]:
my_arr = np.arange(10)
print(my_arr)

my_arr[4:7] = 25
print(my_arr)

arr_slice = my_arr[4:7]
# Need to use arr_slice = my_arr[4:7].copy() to not change the original

# Change the first element of arr_slice to -1
arr_slice[0]= -1

print(arr_slice)
print(my_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 25 25 25  7  8  9]
[-1 25 25]
[ 0  1  2  3 -1 25 25  7  8  9]


# 3D array as image

In [61]:
# array of shape (2, 4, 3)
x = np.array([[[0, 6, 1], [5, 1, 0], [0, -2, 3], [7, 1, 0]], 
             [[3, 0, 0], [1, 2, 0], [5, -4, -1], [4, -1, 0]]])
x

array([[[ 0,  6,  1],
        [ 5,  1,  0],
        [ 0, -2,  3],
        [ 7,  1,  0]],

       [[ 3,  0,  0],
        [ 1,  2,  0],
        [ 5, -4, -1],
        [ 4, -1,  0]]])

In [62]:
x.shape

(2, 4, 3)

In [63]:
np.sum(x, axis = 0)

array([[ 3,  6,  1],
       [ 6,  3,  0],
       [ 5, -6,  2],
       [11,  0,  0]])

In [64]:
np.sum(x, axis = 1)

array([[12,  6,  4],
       [13, -3, -1]])

In [65]:
np.sum(x, axis = 2)

array([[7, 6, 1, 8],
       [3, 3, 0, 3]])

# setup

In [72]:
import sys
!{sys.executable} -m pip install opencv-python

In [73]:
import sys
# Python 3.7 is required
assert sys.version_info >= (3,7)

import cv2 as cv
import numpy as np

# For reproducibility,
np.random.seed(99)

# Make sure that optimization is enabled
if not cv.useOptimized():
    cv.setUseOptimized(True)

cv.useOptimized()

True

# Load display and save the image

In [77]:
img = cv.imread('C:/Users/UTAR/Desktop/lena.jfif')

cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()

-1

In [ ]:
cv.imwrite('lena_save.png', img)

In [1]:
img = cv.imread('C:/Users/UTAR/Desktop/flower.jfif')

img.shape

cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()

NameError: name 'cv' is not defined

In [89]:
flower = img[40:120, 90:175]

cv.imshow('flower',flower)
cv.waitKey(0)
cv.destroyAllWindows()

-1

In [84]:
flower.shape

(80, 85, 3)

In [91]:
img[-80:, :85] = flower

cv.imshow('two flower!', img)
cv.waitKey(0)
cv.destroyAllWindows()

-1

In [104]:
img = cv.imread('C:/Users/UTAR/Desktop/dog.jfif')
img_linear = cv.resize(img, None, fx = 2.5, fy = 2.5, interpolation = cv.INTER_LINEAR)
img_cubic = cv.resize(img, None, fx = 2.5, fy = 2.5, interpolation = cv.INTER_CUBIC)
img_nearest = cv.resize(img, None, fx = 2.5, fy = 2.5, interpolation = cv.INTER_NEAREST)

cv.imshow('linear', img_linear)
cv.imshow('cubic', img_cubic)
cv.imshow('nearest', img_nearest)

cv.waitKey(0)
cv.destroyAllWindows()

-1